name: Test script

on:
  workflow_dispatch

jobs:
  test-set-kv-secret:
    runs-on: ubuntu-latest
    environment: tst
    steps:
        - uses: actions/checkout@v3
    
        - name: Login to Azure
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Test set-kv-secret action
          uses: ./action/set-kv-secret
          with:
            keyvault-name: "web-t-ae-kvt"
            secret-name: "auch-test"
            new-secret-value: "new-secret-value"